apiVersion: apps/v1
kind: Deployment
metadata:
  name: werf-test
spec:
  selector:
    matchLabels:
      app: werf-test
  template:
    metadata:
      labels:
        app: werf-test
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: werf-test
        image: {{ .Values.werf.image.app }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
